name: Rust-OS-check

on:
  push:
    branches:
      - "main"
    paths:
      - 'src/**'
      - 'src-tauri/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'src/**'
      - 'src-tauri/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Check Syntax
      run: cargo check --verbose
    - name: Build Tauri app
      run: cargo tauri dev --verbose
    - name: Run tests
      run: cargo test --verbose
